INSERT INTO questions (category, type, question, options, answer, explanation, sheet) VALUES
('AI Programming', 'mcq', $q$What is the result of bool(0) in Python?$q$, $j$["True", "False", "None", "Error"]$j$::jsonb, 1, $q$In Python, bool(0) evaluates to False because 0 is falsy. Any non-zero number evaluates to True. This is part of Python's truthiness rules.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$Which of the following correctly swaps two variables a and b in Python?$q$, $j$["a = b; b = a", "temp = a; a = b; b = temp", "a, b = b, a", "Both B and C are correct"]$j$::jsonb, 3, $q$Python supports tuple unpacking for swapping: a, b = b, a is the idiomatic way. The classic temp-variable approach (B) also works. Option A fails because a loses its original value before b is updated.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What does the // operator do in Python?$q$, $j$["Regular division", "Floor (integer) division", "Modulo", "Exponentiation"]$j$::jsonb, 1, $q$The // operator performs floor division, which divides and rounds down to the nearest integer. For example, 7 // 2 gives 3, not 3.5.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is the output of type(3.14) in Python?$q$, $j$["<class 'int'>", "<class 'double'>", "<class 'float'>", "<class 'decimal'>"]$j$::jsonb, 2, $q$In Python, decimal numbers are of type float. There is no 'double' or 'decimal' built-in type. type(3.14) returns <class 'float'>.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$Which of the following is a mutable data type in Python?$q$, $j$["tuple", "string", "int", "list"]$j$::jsonb, 3, $q$Lists are mutable — their contents can be changed after creation. Strings, tuples, and integers are immutable; once created their values cannot be modified in-place.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What will the following code print?

for i in range(3):
    print(i, end=' ')$q$, $j$["1 2 3", "0 1 2", "0 1 2 3", "1 2"]$j$::jsonb, 1, $q$range(3) generates 0, 1, 2. The end=' ' argument replaces the default newline with a space, so all values print on one line: 0 1 2.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is the correct way to check if a key exists in a dictionary?$q$, $j$["dict.haskey('key')", "'key' in dict", "dict.contains('key')", "dict.exists('key')"]$j$::jsonb, 1, $q$The 'in' operator is used to check membership in a dictionary (checks keys). dict.has_key() was removed in Python 3, and haskey/contains/exists are not valid dictionary methods.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What does the pop() method do when called on a list without arguments?$q$, $j$["Removes the first element", "Removes the last element and returns it", "Removes all elements", "Raises an error"]$j$::jsonb, 1, $q$list.pop() without arguments removes and returns the last element. You can also pass an index, e.g. list.pop(0) removes the first element.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$Which of the following creates an empty set in Python?$q$, $j$["{}", "set()", "[]", "()"]$j$::jsonb, 1, $q${} creates an empty dictionary, not a set. To create an empty set you must use set(). This is a common Python gotcha.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is the output of 'Python'[::-1]?$q$, $j$["Python", "nohtyP", "Pytho", "Error"]$j$::jsonb, 1, $q$The slice [::-1] reverses a string by stepping through it backwards. 'Python'[::-1] produces 'nohtyP'.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What does the 'pass' statement do in Python?$q$, $j$["Exits the current loop", "Skips the current iteration", "Acts as a placeholder that does nothing", "Returns None from a function"]$j$::jsonb, 2, $q$The 'pass' statement is a no-operation placeholder. It is used when a block is syntactically required but you don't want any code to execute, for example in empty class or function definitions.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is the difference between '==' and 'is' in Python?$q$, $j$["They are identical", "'==' checks value equality; 'is' checks identity (same object in memory)", "'is' checks value; '==' checks identity", "'is' only works for numbers"]$j$::jsonb, 1, $q$'==' compares values: 1 == 1.0 is True. 'is' checks if two variables point to the exact same object in memory. For example, [1,2] == [1,2] is True but [1,2] is [1,2] is False.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is the output of len([1, [2, 3], 4])?$q$, $j$["4", "3", "5", "2"]$j$::jsonb, 1, $q$len() counts the top-level elements of a list. The list has 3 top-level elements: 1, [2,3], and 4. The nested list [2,3] counts as one element.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$Which of the following will produce a TypeError in Python?$q$, $j$["'5' + '3'", "5 + 3", "'5' * 3", "'5' + 3"]$j$::jsonb, 3, $q$You cannot concatenate a string and an integer directly. '5' + 3 raises a TypeError. '5' + '3' gives '53', 5 + 3 gives 8, and '5' * 3 gives '555'.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What does the 'continue' statement do inside a loop?$q$, $j$["Exits the loop immediately", "Skips the rest of the current iteration and moves to the next", "Pauses execution", "Repeats the current iteration"]$j$::jsonb, 1, $q$The 'continue' statement skips any remaining code in the current loop iteration and jumps to the next iteration. Use 'break' to exit the loop entirely.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is a default argument in a Python function?$q$, $j$["An argument that must always be provided", "An argument with a pre-set value used when no value is passed", "The first argument of any function", "An argument passed by reference"]$j$::jsonb, 1, $q$A default argument has a fallback value defined in the function signature, e.g. def greet(name='World'). If no value is passed for that argument, the default is used.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is the output of print(2 ** 3 ** 2)?$q$, $j$["64", "512", "36", "8"]$j$::jsonb, 1, $q$Exponentiation (**) is right-associative in Python, so 2 ** 3 ** 2 is evaluated as 2 ** (3 ** 2) = 2 ** 9 = 512.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$Which method can be used to find the index of an element in a list?$q$, $j$["list.find()", "list.search()", "list.index()", "list.locate()"]$j$::jsonb, 2, $q$list.index(value) returns the index of the first occurrence of the value. If not found it raises a ValueError. find() exists for strings but not lists.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What does the 'global' keyword do inside a function?$q$, $j$["Creates a new global variable", "Allows the function to read and modify a variable defined at the module level", "Makes a variable accessible only inside the function", "Imports all global variables"]$j$::jsonb, 1, $q$Without 'global', assigning to a variable inside a function creates a local variable. The 'global' keyword tells Python to use the module-level variable instead of creating a local one.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is the result of 'hello'.capitalize()?$q$, $j$["HELLO", "Hello", "hELLO", "hello"]$j$::jsonb, 1, $q$capitalize() converts the first character to uppercase and the rest to lowercase. 'hello'.capitalize() returns 'Hello'. It also lowercases any already-uppercase letters after the first.$q$, 'unOfficial Sheet');