INSERT INTO questions (category, type, question, options, answer, explanation, sheet) VALUES
('AI Programming', 'mcq', $q$What does the __str__ method do in a Python class?$q$, $j$["Returns the memory address of the object", "Returns a user-friendly string representation of the object", "Converts all attributes to strings", "It is called automatically when the object is created"]$j$::jsonb, 1, $q$__str__ defines the string representation shown when you call print() or str() on an object. It is meant to be human-readable, unlike __repr__ which is for debugging.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is the output of the following code?

class Animal:
    sound = 'generic'

dog = Animal()
dog.sound = 'woof'
print(Animal.sound)$q$, $j$["woof", "generic", "None", "Error"]$j$::jsonb, 1, $q$Assigning dog.sound = 'woof' creates an instance attribute on dog, it does NOT change the class attribute. Animal.sound remains 'generic'.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is method overriding in Python?$q$, $j$["Defining two methods with the same name but different parameters in the same class", "Redefining a parent class method in a subclass with new behavior", "Calling a method multiple times", "Making a method private"]$j$::jsonb, 1, $q$Method overriding occurs when a subclass provides its own implementation of a method already defined in its parent class. Python uses the most specific (subclass) version when the method is called on a subclass instance.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$Which exception is raised when you try to open a file that does not exist in read mode?$q$, $j$["ValueError", "FileError", "FileNotFoundError", "IOError"]$j$::jsonb, 2, $q$In Python 3, trying to open a non-existent file with open('file.txt', 'r') raises FileNotFoundError, which is a subclass of OSError. IOError is an older alias.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is the purpose of the 'finally' block in exception handling?$q$, $j$["It runs only if no exception occurred", "It runs only if an exception occurred", "It always runs regardless of whether an exception occurred or not", "It re-raises the exception"]$j$::jsonb, 2, $q$The 'finally' block always executes, whether or not an exception was raised. It is typically used for cleanup operations like closing files or releasing resources.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What does the 'with' statement guarantee when used with file operations?$q$, $j$["The file is read line by line", "The file is automatically closed even if an exception occurs", "The file is opened in binary mode", "The file cannot be modified"]$j$::jsonb, 1, $q$The 'with' statement uses a context manager. For files, it guarantees the file is closed properly when the block exits, even if an exception is raised inside the block.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is multiple inheritance in Python?$q$, $j$["A class that defines multiple methods", "A class that inherits from more than one parent class", "Inheriting the same class multiple times", "A method that overrides multiple parent methods"]$j$::jsonb, 1, $q$Multiple inheritance allows a class to inherit attributes and methods from more than one parent class. For example: class C(A, B). Python uses the MRO (Method Resolution Order) to resolve conflicts.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is encapsulation in object-oriented programming?$q$, $j$["Inheriting properties from a parent class", "Bundling data and methods together and restricting direct access to some components", "Creating multiple objects from one class", "Defining multiple methods with the same name"]$j$::jsonb, 1, $q$Encapsulation is the OOP principle of bundling data (attributes) and methods that operate on that data within a class, and restricting external direct access. In Python, this is done with single (_) or double (__) underscores.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What does csv.writer() do?$q$, $j$["Reads a CSV file into a list", "Creates a writer object to write rows to a CSV file", "Converts a list to a CSV string", "Opens a CSV file for editing"]$j$::jsonb, 1, $q$csv.writer() creates a writer object that converts data to CSV format. You then call writer.writerow() or writer.writerows() to write data to the file.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is a list comprehension in Python?$q$, $j$["A way to understand what a list contains", "A concise syntax for creating a new list by applying an expression to each item in an iterable", "A method to sort a list", "A way to merge two lists"]$j$::jsonb, 1, $q$List comprehensions provide a compact way to create lists: [expr for item in iterable if condition]. For example, [x**2 for x in range(5)] creates [0, 1, 4, 9, 16].$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is the difference between instance methods and static methods in Python?$q$, $j$["There is no difference", "Instance methods take 'self' as the first argument; static methods do not and cannot access instance or class data", "Static methods are faster", "Instance methods cannot access class attributes"]$j$::jsonb, 1, $q$Instance methods take 'self' and can access instance and class data. Static methods (decorated with @staticmethod) take no self/cls argument and are essentially regular functions namespaced inside a class.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What does the seek(0) method do on a file object?$q$, $j$["Closes the file", "Moves the file pointer to the beginning of the file", "Reads the first byte", "Checks if the file is empty"]$j$::jsonb, 1, $q$seek(offset) moves the file's read/write pointer to a given byte position. seek(0) resets it to the beginning so you can read the file again from the start.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$Which decorator is used to define a class method in Python?$q$, $j$["@staticmethod", "@classmethod", "@property", "@instancemethod"]$j$::jsonb, 1, $q$@classmethod makes a method receive the class (cls) as its first argument instead of an instance. It can access and modify class state. @staticmethod methods receive neither self nor cls.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What happens when you try to access an attribute that doesn't exist on an object in Python?$q$, $j$["It returns None", "It returns an empty string", "It raises an AttributeError", "It creates the attribute automatically"]$j$::jsonb, 2, $q$Accessing a non-existent attribute raises AttributeError. You can avoid this with hasattr(obj, 'attr') or getattr(obj, 'attr', default) to provide a fallback value.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is the purpose of __del__ in a Python class?$q$, $j$["Deletes a specific attribute", "Is called when the object is about to be garbage collected (destructor)", "Deletes the class from memory", "Removes the last element of a list attribute"]$j$::jsonb, 1, $q$__del__ is the destructor method. It is called when an object is about to be destroyed by the garbage collector. It is rarely used in Python since memory is managed automatically.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What does the 'r+' file mode do?$q$, $j$["Opens for reading only", "Opens for writing only and creates the file if it doesn't exist", "Opens for both reading and writing; the file must already exist", "Opens for reading and appending"]$j$::jsonb, 2, $q$'r+' opens an existing file for both reading and writing. Unlike 'w+', it does NOT truncate the file or create it if it doesn't exist — the file must already exist.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is polymorphism in OOP?$q$, $j$["A class having many attributes", "The ability of different objects to respond to the same method call in different ways", "Inheriting from multiple classes", "Hiding internal data from outside code"]$j$::jsonb, 1, $q$Polymorphism allows objects of different classes to be treated as objects of a common interface. For example, both Dog and Cat classes may have a speak() method that behaves differently for each.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What does writelines() do when writing to a file?$q$, $j$["Writes a single line with a newline at the end", "Writes a list of strings to the file without adding newlines automatically", "Writes each element on a new line automatically", "Appends lines to the end of the file"]$j$::jsonb, 1, $q$writelines() accepts an iterable of strings and writes them to the file. It does NOT add newlines automatically — you must include '\n' in the strings yourself if needed.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What is the use of the 'super()' function in Python?$q$, $j$["Creates a superclass", "Returns a proxy object that allows calling parent class methods", "Checks if a class is a superclass", "Makes all parent class methods available as static methods"]$j$::jsonb, 1, $q$super() returns a proxy object that delegates method calls to a parent class. It is commonly used in __init__ to call the parent constructor: super().__init__() — ensuring the parent is properly initialized.$q$, 'unOfficial Sheet'),
('AI Programming', 'mcq', $q$What does pickle.load() do?$q$, $j$["Serializes a Python object to a file", "Deserializes (reads and reconstructs) a Python object from a binary file", "Loads a text file into memory", "Converts a Python object to JSON"]$j$::jsonb, 1, $q$pickle.load(file) reads a pickled binary file and reconstructs the original Python object. pickle.dump() is the opposite — it serializes an object to a file.$q$, 'unOfficial Sheet');